# Getting Started with pandas

In [47]:
import pandas as pd

In [48]:
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

### Series
- A Series is a one-dimensional array-like object containing a sequence of values

In [49]:
obj=pd.Series([4,7,-5,3])

In [50]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [51]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [52]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [53]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [54]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [55]:
obj*2

0     8
1    14
2   -10
3     6
dtype: int64

In [56]:
import numpy as np

In [57]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [58]:
'b' in obj2

True

In [59]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=pd.Series(sdata)

In [60]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [61]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4=pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [62]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [63]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [64]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [65]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

- you can think about this as being similar to a join operation.

In [66]:
obj4.name = 'population'
obj4.index.name = 'state'

In [67]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### DataFrame

In [68]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [69]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [70]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [71]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
index=['one', 'two', 'three', 'four', 'five', 'six'])

In [72]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

- A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute

In [73]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [74]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [75]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [76]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [77]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

- If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, inserting missing values in any holes

In [78]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt']=val

In [79]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

- Assigning a column that doesn’t exist will create a new column.

In [80]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [81]:
frame3=pd.DataFrame(pop)

In [82]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [83]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [84]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [85]:
pdata = {'Ohio': frame3['Ohio'][:-1],'Nevada': frame3['Nevada'][:2]}

In [86]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

- If a DataFrame’s index and columns have their name attributes set, these will also be displayed

In [87]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

- If the DataFrame’s columns are different dtypes, the dtype of the values array will be chosen to accommodate all of the columns

In [88]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [89]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index=obj.index

In [90]:
index

Index(['a', 'b', 'c'], dtype='object')

In [91]:
index[1:]

Index(['b', 'c'], dtype='object')

- Index objects are immutable and thus can’t be modified by the user

In [92]:
index[1]='d'

TypeError: Index does not support mutable operations

In [93]:
labels=pd.Index(np.arange(3))

In [94]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [95]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [96]:
obj2.index is labels

True

- Unlike Python sets, a pandas Index can contain duplicate labels

In [97]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing

In [98]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [99]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [101]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [102]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [103]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [104]:
frame2=frame.reindex(['a','b','c','d'])

In [105]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [106]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [107]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

### Dropping Entries from an Axis

In [108]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [109]:
new_obj=obj.drop('c')

In [110]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [111]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [112]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])

In [113]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

- Calling drop with a sequence of labels will drop values from the row labels (axis 0)

In [114]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [116]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [117]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [118]:
obj=pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [120]:
obj['b']

1.0

In [121]:
obj[1]

1.0

In [122]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [123]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [124]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [125]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [126]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [127]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])

In [128]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [130]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [131]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [132]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

- The row selection syntax data[:2] is provided as a convenience.
- Passing a single element
or a list to the [] operator selects columns.

In [133]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [134]:
data[data<5]=0

In [135]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

In [136]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [137]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [138]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [139]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [140]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [141]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [143]:
ser = pd.Series(np.arange(3.))

In [144]:
ser[-1]

KeyError: -1

In [145]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [146]:
ser2=pd.Series(np.arange(3.), index=['a','b','c'])

- with a non-integer index, there is no potential for ambiguity

In [147]:
ser2[-1]

2.0

In [148]:
ser[:1]

0    0.0
dtype: float64

In [149]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [150]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment
- When you are adding together objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs.

In [151]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [152]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [153]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [154]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

- In the case of DataFrame, alignment is performed on both the rows and the columns

In [155]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [156]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [157]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [158]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

- returns a DataFrame whose index and columns are the unions of the ones in each DataFrame

### Arithmetic methods with fill values

In [159]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [160]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [161]:
df2.loc[1,'b']=np.nan

In [162]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [163]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [164]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [165]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### Operations between DataFrame and Series

In [166]:
arr = np.arange(12.).reshape((3, 4))

In [167]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [168]:
arr[0]

array([0., 1., 2., 3.])

In [169]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [170]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series=frame.iloc[0]

In [171]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [172]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [174]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

- arithmetic between DataFrame and Series matches the index of the Series on the DataFrame’s columns, broadcasting down the rows
- If an index value is not found in either the DataFrame’s columns or the Series’s index, the objects will be reindexed to form the union:

In [175]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [176]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

- If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods.

In [181]:
series3=frame['d']

In [182]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [183]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [185]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

- In this case we mean to match on the DataFrame’s row index (axis='index' or axis=0) and broadcast across.

### Fuction Application and Mapping

In [186]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [187]:
frame

b         d         e
Utah    1.469199  0.430852  0.090573
Ohio   -0.638705 -0.296152 -0.821055
Texas   0.470794 -0.868065  1.227905
Oregon  0.541306  0.334070 -0.828338

In [188]:
np.abs(frame)

b         d         e
Utah    1.469199  0.430852  0.090573
Ohio    0.638705  0.296152  0.821055
Texas   0.470794  0.868065  1.227905
Oregon  0.541306  0.334070  0.828338

In [189]:
f = lambda x: x.max() - x.min()

In [190]:
frame.apply(f)

b    2.107903
d    1.298917
e    2.056243
dtype: float64

- If you pass axis='columns' to apply, the function will be invoked once per row instead

In [191]:
frame.apply(f, axis='columns')

Utah      1.378626
Ohio      0.524903
Texas     2.095971
Oregon    1.369643
dtype: float64

- The function passed to apply need not return a scalar value; it can also return a Series with multiple values

In [192]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [193]:
frame.apply(f)

b         d         e
min -0.638705 -0.868065 -0.828338
max  1.469199  0.430852  1.227905

- Element-wise Python functions can be used, too.

In [194]:
format = lambda x: '%.2f' % x

In [195]:
frame.applymap(format)

b      d      e
Utah     1.47   0.43   0.09
Ohio    -0.64  -0.30  -0.82
Texas    0.47  -0.87   1.23
Oregon   0.54   0.33  -0.83

- The reason for the name applymap is that Series has a map method for applying an element-wise function

In [196]:
frame['e'].map(format)

Utah       0.09
Ohio      -0.82
Texas      1.23
Oregon    -0.83
Name: e, dtype: object

### Sorting and Ranking

In [197]:
obj=pd.Series(range(4), index=['d','a','b','c'])

In [198]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [199]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [200]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [201]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [202]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [203]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [204]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [205]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [206]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [207]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [209]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

- by default rank breaks ties by assigning each group the mean rank

In [210]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [211]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [212]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

- Ranks can also be assigned according to the order in which they’re observed in the data

In [213]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [214]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})

In [215]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [216]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [217]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [218]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [219]:
obj.index.is_unique

False

- Indexing a label with multiple entries returns a Series, while single entries return a scalar value

In [220]:
obj['a']

a    0
a    1
dtype: int64

In [221]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [222]:
df.loc['b']

0         1         2
b  0.723565 -1.548682  0.265977
b -1.563482  0.259308  0.634522

## Summarizing and Computing Descriptive Statistics

In [223]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
[np.nan, np.nan], [0.75, -1.3]],
index=['a', 'b', 'c', 'd'],
columns=['one', 'two'])

In [224]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [225]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [226]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

- NA values are excluded unless the entire slice (row or column in this case) is NA.
- This can be disabled with the skipna option

In [227]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

- idxmin and idxmax, return indirect statistics like the index value where the minimum or maximum values are attained

In [228]:
df.idxmax()

one    b
two    d
dtype: object

In [229]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

- describe is one such example, producing multiple summary statistics in one shot

In [230]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [232]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [233]:
!pip install pandas-datareader

In [234]:
import pandas_datareader.data as web

In [235]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [236]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [237]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-01-28 -0.034985 -0.019515  0.025891  0.017654
2021-01-29 -0.037421 -0.008078 -0.029172 -0.014690
2021-02-01  0.016520  0.012006  0.033152  0.035740
2021-02-02  0.006337 -0.009126 -0.000584  0.013759
2021-02-03 -0.007778 -0.002679  0.014571  0.073961

In [238]:
returns['MSFT'].corr(returns['IBM'])

0.5407839483969283

In [239]:
returns['MSFT'].cov(returns['IBM'])

0.00015461645601131283

In [241]:
returns.MSFT.corr(returns.IBM)

0.5407839483969283

In [242]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.453987  0.709385  0.651591
IBM   0.453987  1.000000  0.540784  0.506039
MSFT  0.709385  0.540784  1.000000  0.778290
GOOG  0.651591  0.506039  0.778290  1.000000

In [243]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000358  0.000141  0.000233  0.000206
IBM   0.000141  0.000271  0.000155  0.000139
MSFT  0.000233  0.000155  0.000301  0.000225
GOOG  0.000206  0.000139  0.000225  0.000278

In [244]:
returns.corrwith(returns.IBM)

AAPL    0.453987
IBM     1.000000
MSFT    0.540784
GOOG    0.506039
dtype: float64

In [245]:
returns.corrwith(volume)

AAPL   -0.070722
IBM    -0.112012
MSFT   -0.086943
GOOG   -0.134391
dtype: float64

### Unique Values, Value Counts, and Membership

In [246]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [247]:
uniques=obj.unique()

In [249]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [251]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

- The Series is sorted by value in descending order as a convenience

In [252]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
b    2
d    1
dtype: int64

In [253]:
mask=obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [254]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

- Related to isin is the Index.get_indexer method, which gives you an index array from an array of possibly non-distinct values into another array of distinct values

In [255]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [256]:
unique_vals=pd.Series(['c','b','a'])

In [257]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

- you may want to compute a histogram on multiple related columns in a DataFrame.

In [258]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3], 'Qu3': [1, 5, 2, 4, 4]})

In [259]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [260]:
result=data.apply(pd.value_counts).fillna(0)

In [261]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0